runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 2

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: main.app
  secure: always
